### ISSUE TITLE
Different completion numbers between services

### ISSUE THREAD

**Issue by randalla0622** [Mulchman/DestinyRaidStatus#18]
I've noticed that with my account, DRS shows me with more completions than other services do. For example, at this time looking up my account "xaren0622" produces these stats:

- VoG - 13 / 47 / 22 (82)
- CE - 78 / 66 / 30 (174)
- KF - 25 / 103 / 9 (137)
- WotM - 21 / 92 / 7 (120)

However, the stats according to DestinyStatus are:

- VoG - 13 / 40 / 22 (75)
- CE - 69 / 65 / 30 (164)
- KF - 25 / 103 / 9 (137)
- WotM - 21 / 92 / 7 (120)

Are you picking up raid completions from deleted characters? I have one character that I deleted in the TDB expansion, which did both VoG and CE. It would explain the discrepancy.

**Comment by Mulchman** [comment]
Yes, DRS includes raids done on deleted characters.

**Comment by Mulchman** [comment]
Closing this issue.
