### ISSUE TITLE
Destiny 2 Raid Status

### ISSUE THREAD

**Issue by pherum** [Mulchman/DestinyRaidStatus#19]
Please, add stats for Destiny 2 LEVIATHAN RAID

**Comment by Mulchman** [comment]
Thank you for the comment. I plan to add support for Destiny 2.

**Comment by Mulchman** [comment]
It has been quite a while.

Initial Destiny 2 support has been committed, but nothing has been pushed to the user facing URL yet. Expect a full release in the next few days.

It's already better (in terms of a fast/simple raid completion checking tool) than other options like Raid.Report, too, but I don't want to say why just yet. (Hello to them if they have a Google alert or something similar set up.)

**Comment by Mulchman** [comment]
Destiny 2 support has been pushed to the public destinyraidstatus.com site.
