### ISSUE TITLE
Loading gamertag directly from the100.io

### ISSUE THREAD

**Issue by michael-donat** [Mulchman/DestinyRaidStatus#8]
Hey man,

Great job on the tool. I have a PR almost ready to submit with a support for loading all gamertag from the100.io game page. Unfortunately this needs to be done with a server-side component (cors/jsonp limitations) so I was wondering how you host the current solution and whether it would be possible to host a mini node process there too?

Also, sorry for raising an issue for this, but couldn't find any other way of contacting you :)

**Comment by Mulchman** [comment]
Hi there! The current site is Apache on Linux.

I like the idea of being able to batch process a bunch of names. What can I help with?

**Comment by michael-donat** [comment]
Ah, so flat file serving. I will raise that PR with the server component, you can proxy a path in apache to it I suppose, I will leave all details on that PR, just need to put the little monster to bed.

**Comment by Mulchman** [comment]
I labelled that commit wrong. It was for #1 but it's referencing #8 (this one). Woops.

**Comment by Mulchman** [comment]
Any updates?

On a semi-different note I'm making the routing accept names so you can do something like this:

`http://www.destinyraidstatus.com/index.html#/psn/X/Y/Z` [and on and on...]

where `X`, `Y`, and `Z` are all different usernames you want to look up. In theory you can keep going; I don't know what the browser max is. I'm testing with 6 player names I know and it's about 64 characters long not including the platform identifier.

The valid platform identifiers are `psn` and `xbl`.

Commit- https://github.com/Mulchman/DestinyRaidStatus/commit/1b7bd2e42ad3eb2de50114da8ee6473417a3d3f7

**Comment by michael-donat** [comment]
https://github.com/Mulchman/DestinyRaidStatus/pull/14

**Comment by Mulchman** [comment]
I'm thinking about going live with the 100.io scraper. 

You can test here: http://destinyraidstatus.com/test/

**Comment by Mulchman** [comment]
This game has a player with a forward slash in their name? https://www.the100.io/game/968860

**Comment by Mulchman** [comment]
This is another one that breaks the parsing: https://www.the100.io/game/969225

**Comment by Mulchman** [comment]
I'm not sure where to go with this.

Will there be any changes to the100.io side to normalize the name strings? Or should I add more parsing code to the DRS side?

**Comment by michael-donat** [comment]
I'm on holidays till Monday, won't be able to look before then, but any solution will be DRS side.

**Comment by Mulchman** [comment]
Here's an even different format- a forward slash + PSN/XBL being at the end of the name and not the start: https://www.the100.io/game/973296

**Comment by Mulchman** [comment]
1.0.4 is live-

https://destinyraidstatus.com/api/the100/972219
or
Paste a the100.io link, like https://www.the100.io/game/972219, in the `PSN Id`/`Gamertag` box
